version: "3.8"

networks:
  default:
    internal: false
    name: reverse-proxy

services:
  reverse-proxy:
    image: traefik:v2.8
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api.dashboard=true
      # the entrypoints we ant to expose
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # enable ACME (Let's Encrypt): automatic SSL
      - --certificatesresolvers.letsencrypt.acme.email=support@faterium.com
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # global redirect to https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # the acme.json file is required by Let's Encrypt
      - ./acme.json:/etc/traefik/acme/acme.json

  server:
    image: ghcr.io/faterium/faterium-server:latest
    command: serve --http=0.0.0.0:8090
    volumes:
      - ../data:/data
    labels:
      - traefik.enable=true
      # http
      - traefik.http.routers.server-http.entrypoints=web
      - traefik.http.routers.server-http.rule=Host(`localhost`)
      # https
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.rule=Host(`dapi.faterium.com`)
      - traefik.http.routers.server.tls=true
      - traefik.http.routers.server.tls.certresolver=letsencrypt
      # backend port
      - traefik.http.services.server.loadbalancer.server.port=8090

  node:
    image: ghcr.io/faterium/faterium-node:latest
    command:
      - --dev
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --base-path=/data/
    volumes:
      - ../data:/data
    labels:
      - traefik.enable=true
      # http
      - traefik.http.routers.node-http.entrypoints=web
      - traefik.http.routers.node-http.rule=Host(`localhost`) && Path(`/ws`)
      # https
      - traefik.http.routers.node.entrypoints=websecure
      - traefik.http.routers.node.rule=Host(`dapi.faterium.com`) && Path(`/wss`)
      - traefik.http.routers.node.tls=true
      - traefik.http.routers.node.tls.certresolver=letsencrypt
      # backend port
      - traefik.http.services.node.loadbalancer.server.port=9944

  apps:
    image: jacogr/polkadot-js-apps:latest
    environment:
      - WS_URL=wss://dapi.faterium.com/wss
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.site-delete-path.replacepath.path=
      # http
      - traefik.http.routers.apps-http.middlewares=site-delete-path
      - traefik.http.routers.apps-http.entrypoints=web
      - traefik.http.routers.apps-http.rule=Host(`localhost`) && Path(`/apps`)
      # https
      - traefik.http.routers.apps.middlewares=site-delete-path
      - traefik.http.routers.apps.entrypoints=websecure
      - traefik.http.routers.apps.rule=Host(`dapi.faterium.com`) && Path(`/apps`)
      - traefik.http.routers.apps.tls=true
      - traefik.http.routers.apps.tls.certresolver=letsencrypt
      # backend port
      - traefik.http.services.apps.loadbalancer.server.port=80
