version: '3'

services:
  reverse-proxy:
    image: traefik:v2.8
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      # enables web ui on :8080
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # The acme.json file is required by Let's Encrypt
      - ./acme.json:/etc/traefik/acme/acme.json

  server:
    image: ghcr.io/faterium/faterium-server:latest
    command: serve --http=0.0.0.0:8090 --dir=/pb
    volumes:
      - ../data/pb:/pb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server.loadbalancer.server.port=8090"
